### ISSUE TITLE
Bump Groovy to version 2.5?

### ISSUE THREAD

**Issue by lacan** [scijava/scripting-groovy#5]
I've gotten used to the latest Groovy goodness in version 2.5, which seems compatible with Java7+.

Would there be anything against bumping the version on this?

Best

Oli

**Comment by lacan** [comment]
See PR #6

**Comment by ctrueden** [comment]
Fixed by #6; thanks @lacan.

**Comment by imagejan** [comment]
Actually, I'd be in favor of even migrating to version `3.0` soon. The release candidate `3.0.0-rc1` is out since mid-October, and this version comes with [support for a few Java-style things](http://groovy-lang.org/releasenotes/groovy-3.0.html) (like array initialization and lambdas) that make it even easier to run plain-Java code in Groovy 🙂

**Comment by ctrueden** [comment]
@imagejan Have you noticed any issues with backwards compatibility from Groovy 2 to Groovy 3?

**Comment by imagejan** [comment]
@ctrueden so far no, scripting feels like before since I installed `3.0.0-rc1` in my development Fiji installation : ) But I haven't tested extensively yet...

The breaking changes are mainly [package changes](http://groovy-lang.org/releasenotes/groovy-3.0.html#Groovy3.0releasenotes-Splitpackages) of some Groovy classes, but with the old classes being kept as deprecated, AFAICT.

**Comment by imagejan** [comment]
Apart from the package changes mentioned above, there's one more change that *might* affect existing Groovy scripts:

> If a Groovy switch statement has a default branch, it is now required to be the last branch

Nevertheless, I think we should switch to using 3.x soon. What do others think?

**Comment by ctrueden** [comment]
I am in favor of switching now. I added management of all Groovy components at version 3.0.3 to pom-scijava master; see 793e474d5623ad40465cead803aeeb6de99d728d.

**Comment by lacan** [comment]
In favor as well!
